### ISSUE TITLE
Source Code references

### ISSUE THREAD

**Issue by robert-ami** [hughsie/uefi-sbom-best-practices#2]
This phrase is used in the definition of Component and what it should not be.  What does this mean?  What are we alluding to with this?

**Comment by robert-ami** [comment]
That might be the best way.    We just want to make it clear as to what you are referring to when you are spelling out what should not be in a component.

**Comment by felixpgithub** [comment]
There is a requirement in the document to include component SBOM entries for the libraries used by the component, which are essentially source code references (if my understanding is correct). So a component can't be a source code reference, but component SBOM can contain a source code references. Is this the intention?

**Comment by hughsie** [comment]
> So a component can't be a source code reference, but component SBOM can contain source code references. Is this the intention

Yes, that sounds correct. I don't think there's anything stopping vendors like AMI putting links for each component, e.g. saying `<link type="see-also">D:\BIOS\OEM1\edk2\foo.c</link>` although that probably wants to be the SBoM they provided to customers only rather than to the unwashed public.

How about https://github.com/hughsie/uefi-sbom-best-practices/pull/11 for the glossary addition?

**Comment by felixpgithub** [comment]
#11 looks fine
